[[language]]
name = "autohotkey"
scope = "source.autohotkey"
injection-regex = "autohotkey"
file-types = ["autohotkey", "ahk", "ahk2"]
shebangs = ["autohotkey"]
roots = []
auto-format = false
diagnostic-severity = "Warning"
comment-token = ";"
indent = { tab-width = 4, unit = "  " }
# language-server = { command = "mylang-lsp", args = ["--stdio"], environment = { "ENV1" = "value1", "ENV2" = "value2" } }
# config = 
# grammar = 
# formatter = { command = "mylang-formatter" , args = ["--stdin"] }
# text-width = editor.text-width
# workspace-lsp-roots =
